stages:
  - deploy

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://beep.gay
  only:
    - main
  script:
    - git-push ssh://dokku@162.38.112.145:22/beepenmoinsbien